### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by ankane** [ankane/onnxruntime#1]
Plan

- [x] Support more types
- [x] Better output for sequence and map types for `inputs` and `outputs` methods

Blocked - https://github.com/microsoft/onnxruntime/issues/2746

- [x] `ModelMetadata` class
- [x] `model.end_profiling` method

Maybe later

- [ ] `OnnxRuntime.device` method - not available for C API by design
- [ ] Backend API - probably not needed

Python API: https://microsoft.github.io/onnxruntime/python/api_summary.html

**Comment by gsdean** [comment]
We're definitely interested in helping here.  Especially on the `ModelMetadata`.  I haven't had a look at the C API yet, maybe MS will point us in the right directions

**Comment by ankane** [comment]
Hey @gsdean, just fyi, the latest release now supports model metadata. MS recently added it to the C API.
