### ISSUE TITLE
execution_mode argument raises ArgumentError

### ISSUE THREAD

**Issue by lalusaud** [ankane/onnxruntime#5]
Hey @ankane, thank you for this awesome gem! It works perfect with all the other session options except execution_mode.
```
model = OnnxRuntime::Model.new('model.onnx', { execution_mode: :sequential })
```
For some reason, this fails with error message:
```
ArgumentError (wrong number of arguments (2 for 0))
```
Is that a bug? I tried to look into it but seems like it is linked to FFI, which is out of my skills at the moment.

**Comment by ankane** [comment]
Hey @lalusaud, thanks for reporting! Fixed on master.

**Comment by lalusaud** [comment]
Works now on master! Thank you
